postgres_playbook.yml
---
- name: Create a PostgreSQL DB server
  hosts: prod-dbserver
  sudo: yes
  sudo_user: root
  remote_user: ec2-user
  vars_files:
    - vars/main.yml

  roles:
  - roles/postgres
