postgres_playbook.yml
---
- name: Create a PostgreSQL DB server
  hosts: dbserver
  sudo: yes
  sudo_user: root
  remote_user: ubuntu
  vars_files:
    - vars/main.yml

  roles:
  - postgres

- name: Ensure user has access to the database
  sudo_user: postgres
  postgresql_user:
    db={{ db_name }}
    name={{ db_user01 }}
    password={{ db_password }}
    priv=ALL
    state=present

- name: Ensure user does not have unnecessary privileges
  sudo_user: postgres
  postgresql_user:
    name={{ db_user02 }}
    role_attr_flags=NOSUPERUSER,NOCREATEDB
    state=present
