postgres_playbook.yml
---
- name: Create a PostgreSQL DB server
  hosts: dev-dbserver
  sudo: yes
  sudo_user: root
  remote_user: ec2-user
  vars_files:
    - vars/main.yml

  roles:
  - roles/postgres

- name: Ensure user has access to the database
  sudo_user: postgres
  postgresql_user:
    db={{ db_name }}
    name={{ item }}
    role_attr_flags=NOSUPERUSER,NOCREATEDB
    password={{ db_password }}
    state=present
  loop:
    - user1
    - user2
