- name: Ensure bash, OpenSSl, and libssl are the latest versions
  yum: name={{ item }} update_cache=true state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install PostgreSQL
  yum: name={{ item }} update_cache=true state=installed
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
  tags: packages

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  sudo_user: postgres
  postgresql_db: name={{ db_name }}
             encoding='UTF-8'
             lc_collate='en_US.UTF-8'
             lc_ctype='en_US.UTF-8'
             template='template0'
             state=present

- name: Ensure user has access to the database
  sudo_user: postgres
  postgresql_user: db={{ db_name }}
               name={{ db_user_admin }}
               password={{ db_password }}
               priv=ALL
               state=present

- name: Ensure user does not have unnecessary privileges
  sudo_user: postgres
  postgresql_user: name={{ db_user_service1 }}
               role_attr_flags=NOSUPERUSER,NOCREATEDB
               state=present
- name: Make Postgres cluster directory
  command: mkdir /var/lib/pgsql

- name: Change ownership
  command: chown postgres /usr/local/pgsql

- name: Initialize Postgres DB cluster
  command: initdb -D /var/lib/pgsql/data

- name: copy Postgres config file
  template: src=templates/posgres.conf.j2 dest=/var/lib/pgsql/data/postgresql.conf
    mode=0644
